In [1]:
import numpy as np

## Numpy Arrays

In [2]:
# Creating Numpy Array
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [5]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0,10,3) # linearly spaced

array([ 0.,  5., 10.])

In [11]:
np.linspace(0, 10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(1)

array([0.6040367])

In [14]:
np.random.rand(4,2)

array([[0.62587183, 0.72130895],
       [0.08902943, 0.12920874],
       [0.56082283, 0.91826765],
       [0.88328103, 0.51288663]])

In [15]:
np.random.randn(5) # standard normal distribution

array([ 0.44467123, -0.83248499, -1.08126039,  0.55186093,  0.38322382])

In [16]:
np.random.randint(1, 100)

87

In [17]:
np.random.randint(1,100,10)

array([54, 36,  1, 93, 55, 83,  6, 84, 37, 92])

In [18]:
arr = np.arange(25)
ranarr = np.random.randint(0,100,10)

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.shape

(25,)

In [21]:
arr.dtype

dtype('int64')

In [22]:
ranarr

array([32, 44, 86, 21, 21,  7, 15, 54, 32, 97])

In [23]:
ranarr.max()

97

In [24]:
ranarr.argmax()

9

In [25]:
ranarr.argmin()

5

## Numpy Operations

In [26]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [29]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [31]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [32]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [33]:
np.max(arr)

9

In [34]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## Numpy Indexing and Selection

In [35]:
# bracket indexing
arr[6]

6

In [36]:
arr[1:5]

array([1, 2, 3, 4])

In [37]:
arr[:5]

array([0, 1, 2, 3, 4])

In [38]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[0:5] = 100 # broadcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [40]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [41]:
slice_of_arr[:] = 99
slice_of_arr # pointer, change the original array as well

array([99, 99, 99, 99, 99, 99])

In [42]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [43]:
arr_copy = arr.copy()
arr_copy[:] = 200

In [44]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [46]:
# matrix[row, col]
# matrix[row][col]
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
mat[0]

array([ 5, 10, 15])

In [48]:
mat[1][1] # mat[1,1]

25

In [49]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [50]:
mat.sum()

225

In [51]:
mat.sum(axis=0)

array([60, 75, 90])

In [52]:
mat.sum(axis=1)

array([ 30,  75, 120])

In [53]:
# CONDITIONAL SELECTION
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [56]:
arr[arr>4] #conditional selection

array([ 5,  6,  7,  8,  9, 10])

## Exercise

In [57]:
# create an array of 10 fives
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [58]:
# create an array of all the even integeres from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [59]:
# create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])